name: Docker Build and Push to ECR

on:
  push:
    branches: [main]
    paths:
      - 'docker-app/**'
      - '.github/workflows/docker-deploy.yml'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: docker-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIA22BK4CGMHBPBVZ4X
        aws-secret-access-key: 8xdvrsYCMT9CzaelkliiPZsU1VR8Mn5JdLk1zwv6k
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/sample-app-repo:${{ github.sha }} .
        docker tag ${{ steps.login-ecr.outputs.registry }}/sample-app-repo:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/sample-app-repo:latest

    - name: Push to ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/sample-app-repo:${{ github.sha }}
        docker push ${{ steps.login-ecr.outputs.registry }}/sample-app-repo:latest

    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster college-demo-cluster-dev \
          --service sample-app-service \
          --force-new-deployment